name: CI
on: pull_request
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  BUILD_TOKENS_PREFLIGHT: ${{ secrets.BUILD_TOKENS_PREFLIGHT }}
  AWS_DEFAULT_REGION: us-east-1
  AWS_DEFAULT_OUTPUT: json
jobs:
  test:
    name: Lint/Test
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: Brightspace/third-party-actions@actions/checkout
      - name: Setup Node
        uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version: '14'
      - name: Add CodeArtifact npm registry
        uses: Brightspace/codeartifact-actions/npm/add-registry@v1.5.1
        with:
          auth-token: '${{secrets.CODEARTIFACT_AUTH_TOKEN}}'
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Unit Tests (SauceLabs)
        env:
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY_DESIRE2LEARN }}
          SAUCE_USERNAME: Desire2Learn
        run: npm run test:polymer:sauce
